INPUT_FILE = "_xml/index.xml"
OUTPUT_FILE = "_rst/index.rst"

INTRO_FILE = "page_index.rst"
INDEX_TITLE = "Predicated Tree"

LANGUAGE = "cpp"
ML_SPECIFIER_MODIFIER_LIST = true
ESCAPE_ASTERISKS = true
ESCAPE_TRAILING_UNDERSCORES = true
VERBATIM_TO_CODE_BLOCK = "none"

SORT_GROUPS_BY = "id"
SECTION_TO_RUBRIC = true
PRE_BODY_NL = false
ML_PARAM_LIST_COUNT_THRESHOLD = 10
